# Generated by Django 5.2.5 on 2025-09-01 08:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200, verbose_name='Слово')),
                ('translation', models.CharField(max_length=200, verbose_name='Перевод')),
                ('example', models.TextField(blank=True, null=True, verbose_name='Пример использования')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('level', models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default='beginner', max_length=20, verbose_name='Уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Карточка',
                'verbose_name_plural': 'Карточки',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующее повторение')),
                ('ease_factor', models.FloatField(default=2.5, verbose_name='Фактор лёгкости')),
                ('interval', models.IntegerField(default=0, verbose_name='Интервал (дни)')),
                ('repetitions', models.IntegerField(default=0, verbose_name='Число повторений')),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cards.card', verbose_name='Карточка')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание повторений',
            },
        ),
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cards', models.IntegerField(default=0, verbose_name='Всего карточек')),
                ('learned_cards', models.IntegerField(default=0, verbose_name='Выучено карточек')),
                ('review_streak', models.IntegerField(default=0, verbose_name='Серия повторений')),
                ('last_reviewed', models.DateTimeField(blank=True, null=True, verbose_name='Последнее повторение')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статистика пользователя',
                'verbose_name_plural': 'Статистика пользователей',
            },
        ),
    ]
