# Generated by Django 5.2.5 on 2025-09-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_userstats_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstats',
            name='reminder_time',
            field=models.TimeField(default='09:00', verbose_name='Время напоминания'),
        ),
    ]
