# Generated by Django 5.2.5 on 2025-09-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_userstats_reminder_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='interval',
            field=models.IntegerField(default=1, verbose_name='Интервал (дни)'),
        ),
    ]
